services:
  web:
    build: ./
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=beldev
      - MYSQL_DATABASE=social_network
      - MYSQL_PASSWORD=dev
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
volumes:
  db: